//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDesktop2020.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int Id { get; set; }
        public string Comentario1 { get; set; }
        public Nullable<System.DateTime> DataHoraComentario { get; set; }
        public Nullable<int> IdJogo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Jogos Jogos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
