//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDesktop2020.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogadores
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int NumeroCamisa { get; set; }
        public Nullable<int> SelecaoId { get; set; }
        public Nullable<int> PosicaoId { get; set; }
    
        public virtual Posicoes Posicoes { get; set; }
        public virtual Selecoes Selecoes { get; set; }
    }
}
