//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDesktop2020.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jogos()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SelecaoCasaId { get; set; }
        public Nullable<int> PlacarCasa { get; set; }
        public Nullable<int> SelecaoVisitanteId { get; set; }
        public Nullable<int> PlacarVisitante { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> RodadaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        public virtual Rodadas Rodadas { get; set; }
        public virtual Selecoes Selecoes { get; set; }
        public virtual Selecoes Selecoes1 { get; set; }
    }
}
