//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDesktop2020.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notificacoes()
        {
            this.NotificacoesUsuarios = new HashSet<NotificacoesUsuarios>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataHoraCadastro { get; set; }
        public Nullable<System.DateTime> DataHoraEnvio { get; set; }
        public string Importancia { get; set; }
        public Nullable<int> SelecaoId { get; set; }
    
        public virtual Selecoes Selecoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificacoesUsuarios> NotificacoesUsuarios { get; set; }
    }
}
