//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiorentinoForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benefits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Benefits()
        {
            this.PersonBenefits = new HashSet<PersonBenefits>();
        }
    
        public int ID { get; set; }
        public decimal DiscountPercentage { get; set; }
        public Nullable<int> DiscountTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual DiscountTypes DiscountTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonBenefits> PersonBenefits { get; set; }
    }
}
