//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiorentinoForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommutingPerson
    {
        public int ID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> TransportationID { get; set; }
    
        public virtual Commuting Commuting { get; set; }
        public virtual People People { get; set; }
    }
}
