//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiorentinoForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaterial
    {
        public int ID { get; set; }
        public Nullable<int> ServiceOrderID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual ServiceOrder ServiceOrder { get; set; }
    }
}
