//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiorentinoForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ServiceOrderID { get; set; }
        public Nullable<int> ContainerOccupationID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
    
        public virtual ContainerOccupation ContainerOccupation { get; set; }
        public virtual PaymentTypes PaymentTypes { get; set; }
        public virtual People People { get; set; }
        public virtual ServiceOrder ServiceOrder { get; set; }
    }
}
