//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiorentinoForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonBenefits
    {
        public int ID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> BenefitID { get; set; }
        public string CancelationDate { get; set; }
        public string Amount { get; set; }
        public Nullable<int> Occurrence { get; set; }
        public Nullable<System.DateTime> SolicitationDate { get; set; }
    
        public virtual Benefits Benefits { get; set; }
        public virtual People People { get; set; }
    }
}
