//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop2020.Modal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sessao5Entities : DbContext
    {
        public Sessao5Entities()
            : base("name=Sessao5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comentario> Comentario { get; set; }
        public virtual DbSet<Jogadores> Jogadores { get; set; }
        public virtual DbSet<Jogos> Jogos { get; set; }
        public virtual DbSet<Notificacoes> Notificacoes { get; set; }
        public virtual DbSet<NotificacoesUsuarios> NotificacoesUsuarios { get; set; }
        public virtual DbSet<Posicoes> Posicoes { get; set; }
        public virtual DbSet<Rodadas> Rodadas { get; set; }
        public virtual DbSet<Selecoes> Selecoes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
