//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogos
    {
        public int idJogo { get; set; }
        public System.DateTime data { get; set; }
        public int idCompeticao { get; set; }
        public int selecao1 { get; set; }
        public int placar1 { get; set; }
        public bool penalt1 { get; set; }
        public int selecao2 { get; set; }
        public int placar2 { get; set; }
        public bool penalt2 { get; set; }
    
        public virtual Competicao Competicao { get; set; }
        public virtual Selecao Selecao { get; set; }
        public virtual Selecao Selecao3 { get; set; }
    }
}
