//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Notificacao = new HashSet<Notificacao>();
            this.PerguntaUsuario = new HashSet<PerguntaUsuario>();
        }
    
        public int idUsuario { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public byte[] foto { get; set; }
        public string apelido { get; set; }
        public string timeFavorito { get; set; }
        public string corFavorita { get; set; }
        public System.DateTime nascimento { get; set; }
        public int idIndicado { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public System.DateTime dataConvite { get; set; }
        public bool recebeNotificacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacao> Notificacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerguntaUsuario> PerguntaUsuario { get; set; }
    }
}
